extend = '../pyproject.toml'

[lint]
extend-select = ['D']
ignore = ['D102', 'D105', 'D107', 'D415']

[lint.isort]
known-first-party = ['deepquantum']
known-third-party = []

[lint.pydocstyle]
convention = 'google'
